// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl

package naming

// MountFlag is a bit mask of options to the mount call.
type MountFlag uint32

// VDLMountedServer represents a server mounted on a specific name.
type VDLMountedServer struct {
	// Server is the OA that's mounted.
	Server string
	// TTL is the remaining time (in seconds) before the mount entry expires.
	TTL uint32
}

// MountEntry represents a given name mounted in the mounttable.
type VDLMountEntry struct {
	// Name is the mounted name.
	Name string
	// Servers (if present) specifies the mounted names.
	Servers []VDLMountedServer
	// MT is true if the servers represent mount tables.
	MT bool
}

const Replace = MountFlag(1) // Replace means the mount should replace what is currently at the mount point

const MT = MountFlag(2) // MT means that the target server is a mount table.
