// This file was auto-generated by the veyron vdl tool.
// Source: builtin.vdl

package vdl

// TODO(toddw): Remove IDAction and put fields directly into Error.
type IDAction struct {
	ID     string // Error ID, used to uniquely identify each error.
	Action uint32 // Action code expected to be performed by the receiver.
}

func (IDAction) __VDLReflect(struct {
	Name string "v.io/core/veyron2/vdl.IDAction"
}) {
}

// WireError is the wire representation for the built-in error type.  Errors and
// exceptions in each programming environment are converted to this type to
// ensure wire compatibility.  Generated code for each environment provides
// automatic conversions into idiomatic native representations.
type WireError struct {
	IDAction  IDAction
	Msg       string   // Error message, may be empty.
	ParamList []AnyRep // Variadic parameters contained in the error.
}

func (WireError) __VDLReflect(struct {
	Name string "v.io/core/veyron2/vdl.WireError"
}) {
}

func init() {
	Register((*IDAction)(nil))
	Register((*WireError)(nil))
}
