// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was auto-generated by the vanadium vdl tool.
// Source: types.vdl

package uniqueid

import (
	// VDL system imports
	"v.io/v23/vdl"
)

// An Id is a likely globally unique identifier.
type Id [16]byte

func (Id) __VDLReflect(struct {
	Name string `vdl:"v.io/v23/uniqueid.Id"`
}) {
}

func init() {
	vdl.Register((*Id)(nil))
}
