// This file was auto-generated by the veyron vdl tool.
// Source: vomdata.vdl

package testdata

import (
	// The non-user imports are prefixed with "__" to prevent collisions.
	__vdl "veyron.io/veyron/veyron2/vdl"
	__vdlutil "veyron.io/veyron/veyron2/vdl/vdlutil"
)

// TestCase represents an individual testcase for vom encoding and decoding.
type TestCase struct {
	Name  string        // Name of the testcase
	Value __vdlutil.Any // Value to test
	Hex   string        // Hex pattern representing vom encoding of Value
}

func (TestCase) __VDLReflect(struct {
	Name string "veyron.io/veyron/veyron2/vom2/testdata.TestCase"
}) {
}

func init() {
	__vdl.Register(TestCase{})
}

// Tests contains the testcases to use to test vom encoding and decoding.
var Tests = []TestCase{
	{
		Name:  "true",
		Value: true,
		Hex:   "800601",
	},
	{
		Name:  "false",
		Value: false,
		Hex:   "800600",
	},
	{
		Name:  "\"\"",
		Value: "",
		Hex:   "800800",
	},
	{
		Name:  "\"abc\"",
		Value: "abc",
		Hex:   "800803616263",
	},
	{
		Name:  "[]byte(\"\")",
		Value: []byte(""),
		Hex:   "803400",
	},
	{
		Name:  "[]byte(\"def\")",
		Value: []byte("def"),
		Hex:   "803403646566",
	},
	{
		Name:  "byte(0)",
		Value: byte(0),
		Hex:   "800a00",
	},
	{
		Name:  "byte(127)",
		Value: byte(127),
		Hex:   "800a7f",
	},
	{
		Name:  "uint16(0)",
		Value: uint16(0),
		Hex:   "800c00",
	},
	{
		Name:  "uint16(1)",
		Value: uint16(1),
		Hex:   "800c01",
	},
	{
		Name:  "uint16(2)",
		Value: uint16(2),
		Hex:   "800c02",
	},
	{
		Name:  "uint16(63)",
		Value: uint16(63),
		Hex:   "800c3f",
	},
	{
		Name:  "uint16(64)",
		Value: uint16(64),
		Hex:   "800c40",
	},
	{
		Name:  "uint16(127)",
		Value: uint16(127),
		Hex:   "800c7f",
	},
	{
		Name:  "uint16(128)",
		Value: uint16(128),
		Hex:   "800cff80",
	},
	{
		Name:  "uint16(255)",
		Value: uint16(255),
		Hex:   "800cffff",
	},
	{
		Name:  "uint16(256)",
		Value: uint16(256),
		Hex:   "800cfe0100",
	},
	{
		Name:  "uint16(32766)",
		Value: uint16(32766),
		Hex:   "800cfe7ffe",
	},
	{
		Name:  "uint16(32767)",
		Value: uint16(32767),
		Hex:   "800cfe7fff",
	},
	{
		Name:  "uint16(65534)",
		Value: uint16(65534),
		Hex:   "800cfefffe",
	},
	{
		Name:  "uint16(65535)",
		Value: uint16(65535),
		Hex:   "800cfeffff",
	},
	{
		Name:  "uint32(0)",
		Value: uint32(0),
		Hex:   "800e00",
	},
	{
		Name:  "uint32(8388606)",
		Value: uint32(8388606),
		Hex:   "800efd7ffffe",
	},
	{
		Name:  "uint32(8388607)",
		Value: uint32(8388607),
		Hex:   "800efd7fffff",
	},
	{
		Name:  "uint32(16777214)",
		Value: uint32(16777214),
		Hex:   "800efdfffffe",
	},
	{
		Name:  "uint32(16777215)",
		Value: uint32(16777215),
		Hex:   "800efdffffff",
	},
	{
		Name:  "uint32(2147483646)",
		Value: uint32(2147483646),
		Hex:   "800efc7ffffffe",
	},
	{
		Name:  "uint32(2147483647)",
		Value: uint32(2147483647),
		Hex:   "800efc7fffffff",
	},
	{
		Name:  "uint32(4294967294)",
		Value: uint32(4294967294),
		Hex:   "800efcfffffffe",
	},
	{
		Name:  "uint32(4294967295)",
		Value: uint32(4294967295),
		Hex:   "800efcffffffff",
	},
	{
		Name:  "uint64(0)",
		Value: uint64(0),
		Hex:   "801000",
	},
	{
		Name:  "int16(0)",
		Value: int16(0),
		Hex:   "801200",
	},
	{
		Name:  "int16(1)",
		Value: int16(1),
		Hex:   "801202",
	},
	{
		Name:  "int16(2)",
		Value: int16(2),
		Hex:   "801204",
	},
	{
		Name:  "int16(63)",
		Value: int16(63),
		Hex:   "80127e",
	},
	{
		Name:  "int16(64)",
		Value: int16(64),
		Hex:   "8012ff80",
	},
	{
		Name:  "int16(127)",
		Value: int16(127),
		Hex:   "8012fffe",
	},
	{
		Name:  "int16(128)",
		Value: int16(128),
		Hex:   "8012fe0100",
	},
	{
		Name:  "int16(255)",
		Value: int16(255),
		Hex:   "8012fe01fe",
	},
	{
		Name:  "int16(256)",
		Value: int16(256),
		Hex:   "8012fe0200",
	},
	{
		Name:  "int16(32766)",
		Value: int16(32766),
		Hex:   "8012fefffc",
	},
	{
		Name:  "int16(32767)",
		Value: int16(32767),
		Hex:   "8012fefffe",
	},
	{
		Name:  "int32(0)",
		Value: int32(0),
		Hex:   "801400",
	},
	{
		Name:  "int32(8388606)",
		Value: int32(8388606),
		Hex:   "8014fdfffffc",
	},
	{
		Name:  "int32(8388607)",
		Value: int32(8388607),
		Hex:   "8014fdfffffe",
	},
	{
		Name:  "int32(16777214)",
		Value: int32(16777214),
		Hex:   "8014fc01fffffc",
	},
	{
		Name:  "int32(16777215)",
		Value: int32(16777215),
		Hex:   "8014fc01fffffe",
	},
	{
		Name:  "int32(2147483646)",
		Value: int32(2147483646),
		Hex:   "8014fcfffffffc",
	},
	{
		Name:  "int32(2147483647)",
		Value: int32(2147483647),
		Hex:   "8014fcfffffffe",
	},
	{
		Name:  "int64(0)",
		Value: int64(0),
		Hex:   "801600",
	},
	{
		Name:  "int16(-1)",
		Value: int16(-1),
		Hex:   "801201",
	},
	{
		Name:  "int16(-2)",
		Value: int16(-2),
		Hex:   "801203",
	},
	{
		Name:  "int16(-64)",
		Value: int16(-64),
		Hex:   "80127f",
	},
	{
		Name:  "int16(-65)",
		Value: int16(-65),
		Hex:   "8012ff81",
	},
	{
		Name:  "int16(-128)",
		Value: int16(-128),
		Hex:   "8012ffff",
	},
	{
		Name:  "int16(-129)",
		Value: int16(-129),
		Hex:   "8012fe0101",
	},
	{
		Name:  "int16(-256)",
		Value: int16(-256),
		Hex:   "8012fe01ff",
	},
	{
		Name:  "int16(-257)",
		Value: int16(-257),
		Hex:   "8012fe0201",
	},
	{
		Name:  "int16(-32767)",
		Value: int16(-32767),
		Hex:   "8012fefffd",
	},
	{
		Name:  "int16(-32768)",
		Value: int16(-32768),
		Hex:   "8012feffff",
	},
	{
		Name:  "int32(-8388607)",
		Value: int32(-8388607),
		Hex:   "8014fdfffffd",
	},
	{
		Name:  "int32(-8388608)",
		Value: int32(-8388608),
		Hex:   "8014fdffffff",
	},
	{
		Name:  "int32(-16777215)",
		Value: int32(-16777215),
		Hex:   "8014fc01fffffd",
	},
	{
		Name:  "int32(-16777216)",
		Value: int32(-16777216),
		Hex:   "8014fc01ffffff",
	},
	{
		Name:  "int32(-2147483647)",
		Value: int32(-2147483647),
		Hex:   "8014fcfffffffd",
	},
	{
		Name:  "int32(-2147483648)",
		Value: int32(-2147483648),
		Hex:   "8014fcffffffff",
	},
	{
		Name:  "float32(0)",
		Value: float32(0),
		Hex:   "801800",
	},
	{
		Name:  "float32(32.5)",
		Value: float32(32.5),
		Hex:   "8018fd404040",
	},
	{
		Name:  "float32(-32.5)",
		Value: float32(-32.5),
		Hex:   "8018fd4040c0",
	},
	{
		Name:  "float64(0)",
		Value: float64(0),
		Hex:   "801a00",
	},
	{
		Name:  "float64(64.5)",
		Value: float64(64.5),
		Hex:   "801afd205040",
	},
	{
		Name:  "float64(-64.5)",
		Value: float64(-64.5),
		Hex:   "801afd2050c0",
	},
	{
		Name:  "complex64(0)",
		Value: complex64(0),
		Hex:   "801c020000",
	},
	{
		Name:  "complex64(64.5+64.5i)",
		Value: complex64(64.5 + 64.5i),
		Hex:   "801c08fd205040fd205040",
	},
	{
		Name:  "complex64(64.5-64.5i)",
		Value: complex64(64.5 - 64.5i),
		Hex:   "801c08fd205040fd2050c0",
	},
	{
		Name:  "complex128(0)",
		Value: complex128(0),
		Hex:   "801e020000",
	},
	{
		Name:  "complex128(128.5+128.5i)",
		Value: complex128(128.5 + 128.5i),
		Hex:   "801e08fd106040fd106040",
	},
	{
		Name:  "complex128(128.5-128.5i)",
		Value: complex128(128.5 - 128.5i),
		Hex:   "801e08fd106040fd1060c0",
	},
	{
		Name:  "NBool(true)",
		Value: NBool(true),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff8201",
	},
	{
		Name:  "NBool(false)",
		Value: NBool(false),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff8200",
	},
	{
		Name:  "NString(\"\")",
		Value: NString(""),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e537472696e67020400ff8200",
	},
	{
		Name:  "NString(\"abc\")",
		Value: NString("abc"),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e537472696e67020400ff8203616263",
	},
	{
		Name:  "NByteSlice(\"\")",
		Value: NByteSlice(""),
		Hex:   "80ff8137130131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e42797465536c696365020500ff8200",
	},
	{
		Name:  "NByteSlice(\"def\")",
		Value: NByteSlice("def"),
		Hex:   "80ff8137130131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e42797465536c696365020500ff8203646566",
	},
	{
		Name:  "NByte(0)",
		Value: NByte(0),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e42797465020500ff8200",
	},
	{
		Name:  "NByte(127)",
		Value: NByte(127),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e42797465020500ff827f",
	},
	{
		Name:  "NUint16(0)",
		Value: NUint16(0),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e743136020600ff8200",
	},
	{
		Name:  "NUint16(65535)",
		Value: NUint16(65535),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e743136020600ff82feffff",
	},
	{
		Name:  "NUint32(0)",
		Value: NUint32(0),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e743332020700ff8200",
	},
	{
		Name:  "NUint32(4294967295)",
		Value: NUint32(4294967295),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e743332020700ff82fcffffffff",
	},
	{
		Name:  "NUint64(0)",
		Value: NUint64(0),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e743634020800ff8200",
	},
	{
		Name:  "NInt16(0)",
		Value: NInt16(0),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743136020900ff8200",
	},
	{
		Name:  "NInt16(32767)",
		Value: NInt16(32767),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743136020900ff82fefffe",
	},
	{
		Name:  "NInt16(-32768)",
		Value: NInt16(-32768),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743136020900ff82feffff",
	},
	{
		Name:  "NInt32(0)",
		Value: NInt32(0),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743332020a00ff8200",
	},
	{
		Name:  "NInt32(2147483647)",
		Value: NInt32(2147483647),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743332020a00ff82fcfffffffe",
	},
	{
		Name:  "NInt32(-2147483648)",
		Value: NInt32(-2147483648),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743332020a00ff82fcffffffff",
	},
	{
		Name:  "NInt64(0)",
		Value: NInt64(0),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743634020b00ff8200",
	},
	{
		Name:  "NFloat32(0)",
		Value: NFloat32(0),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743332020c00ff8200",
	},
	{
		Name:  "NFloat32(32.5)",
		Value: NFloat32(32.5),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743332020c00ff82fd404040",
	},
	{
		Name:  "NFloat32(-32.5)",
		Value: NFloat32(-32.5),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743332020c00ff82fd4040c0",
	},
	{
		Name:  "NFloat64(0)",
		Value: NFloat64(0),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743634020d00ff8200",
	},
	{
		Name:  "NFloat64(64.5)",
		Value: NFloat64(64.5),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743634020d00ff82fd205040",
	},
	{
		Name:  "NFloat64(-64.5)",
		Value: NFloat64(-64.5),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743634020d00ff82fd2050c0",
	},
	{
		Name:  "NComplex64(0)",
		Value: NComplex64(0),
		Hex:   "80ff8137100131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c65783634020e00ff82020000",
	},
	{
		Name:  "NComplex64(64.5+64.5i)",
		Value: NComplex64(64.5 + 64.5i),
		Hex:   "80ff8137100131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c65783634020e00ff8208fd205040fd205040",
	},
	{
		Name:  "NComplex64(64.5-64.5i)",
		Value: NComplex64(64.5 - 64.5i),
		Hex:   "80ff8137100131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c65783634020e00ff8208fd205040fd2050c0",
	},
	{
		Name:  "NComplex128(0)",
		Value: NComplex128(0),
		Hex:   "80ff8138100132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c6578313238020f00ff82020000",
	},
	{
		Name:  "NComplex128(128.5+128.5i)",
		Value: NComplex128(128.5 + 128.5i),
		Hex:   "80ff8138100132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c6578313238020f00ff8208fd106040fd106040",
	},
	{
		Name:  "NComplex128(128.5-128.5i)",
		Value: NComplex128(128.5 - 128.5i),
		Hex:   "80ff8138100132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c6578313238020f00ff8208fd106040fd1060c0",
	},
	{
		Name: "[2]uint64{1, 2}",
		Value: [2]uint64{
			1,
			2,
		},
		Hex: "80ff81081201000208030200ff82020102",
	},
	{
		Name: "NArray2Uint64{1, 2}",
		Value: NArray2Uint64{
			1,
			2,
		},
		Hex: "80ff813c120134766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e41727261793255696e7436340208030200ff82020102",
	},
	{
		Name: "[]uint64{1, 2}",
		Value: []uint64{
			1,
			2,
		},
		Hex: "80ff8106130100020800ff8203020102",
	},
	{
		Name: "NListUint64{1, 2}",
		Value: NListUint64{
			1,
			2,
		},
		Hex: "80ff8138130132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4c69737455696e743634020800ff8203020102",
	},
	{
		Name: "set[uint64]{1}",
		Value: map[uint64]struct{}{
			1: struct{}{},
		},
		Hex: "80ff8106140100020800ff82020101",
	},
	{
		Name: "NSetUint64{1}",
		Value: NSetUint64{
			1: struct{}{},
		},
		Hex: "80ff8137140131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e53657455696e743634020800ff82020101",
	},
	{
		Name: "map[uint64]string{1: \"abc\"}",
		Value: map[uint64]string{
			1: "abc",
		},
		Hex: "80ff81081501000208030400ff8206010103616263",
	},
	{
		Name: "NMapUint64String{1: \"abc\"}",
		Value: NMapUint64String{
			1: "abc",
		},
		Hex: "80ff813f150137766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4d617055696e743634537472696e670208030400ff8206010103616263",
	},
	{
		Name: "NStruct{A: true, B: \"abc\", C: 123}",
		Value: NStruct{
			A: true,
			B: "abc",
			C: 123,
		},
		Hex: "80ff814616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff820b0101020361626303fff600",
	},
	{
		Name:  "?NStruct(nil)",
		Value: (*NStruct)(nil),
		Hex:   "80ff834616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff81061d0100024200ff820100",
	},
	{
		Name:  "?NStruct{}",
		Value: &NStruct{},
		Hex:   "80ff834616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff81061d0100024200ff82080101000200030000",
	},
	{
		Name: "?NStruct{A: true, B: \"abc\", C: 123}",
		Value: &NStruct{
			A: true,
			B: "abc",
			C: 123,
		},
		Hex: "80ff834616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff81061d0100024200ff820c010101020361626303fff600",
	},
	{
		Name:  "NEnum.A",
		Value: NEnumA,
		Hex:   "80ff813811012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e456e756d020301410142014300ff8200",
	},
	{
		Name:  "NEnum.B",
		Value: NEnumB,
		Hex:   "80ff813811012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e456e756d020301410142014300ff8201",
	},
	{
		Name:  "NEnum.C",
		Value: NEnumC,
		Hex:   "80ff813811012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e456e756d020301410142014300ff8202",
	},
	{
		Name:  "NOneOf{A: true}",
		Value: NOneOf(NOneOfA{true}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff82020101",
	},
	{
		Name:  "NOneOf{A: false}",
		Value: NOneOf(NOneOfA{false}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff82020100",
	},
	{
		Name:  "NOneOf{B: \"\"}",
		Value: NOneOf(NOneOfB{""}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff82020200",
	},
	{
		Name:  "NOneOf{B: \"abc\"}",
		Value: NOneOf(NOneOfB{"abc"}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff82050203616263",
	},
	{
		Name:  "NOneOf{C: 0}",
		Value: NOneOf(NOneOfC{int64(0)}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff82020300",
	},
	{
		Name:  "NOneOf{C: 123}",
		Value: NOneOf(NOneOfC{int64(123)}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff820303fff6",
	},
	{
		Name:  "NOneOf{C: -123}",
		Value: NOneOf(NOneOfC{int64(-123)}),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b0000ff820303fff5",
	},
	{
		Name:  "MBool(true)",
		Value: MBool(true),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff8201",
	},
	{
		Name:  "MBool(false)",
		Value: MBool(false),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff8200",
	},
	{
		Name: "MStruct{A: true, B: true, C: true}",
		Value: MStruct{
			A: true,
			B: true,
			C: true,
			E: __vdl.TypeOf((*__vdlutil.Any)(nil)),
		},
		Hex: "80ff833210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff853210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff894616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff87061d0100024500ff815816012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d537472756374020601014102030001014202420001014302430001014402440001014502020001014602010000ff820d01010201030104000501060000",
	},
	{
		Name: "MStruct{}",
		Value: MStruct{
			E: __vdl.TypeOf((*__vdlutil.Any)(nil)),
		},
		Hex: "80ff833210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff853210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff894616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff87061d0100024500ff815816012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d537472756374020601014102030001014202420001014302430001014402440001014502020001014602010000ff820d01000200030004000501060000",
	},
	{
		Name: "MStruct{D: {}}",
		Value: MStruct{
			D: &NStruct{},
			E: __vdl.TypeOf((*__vdlutil.Any)(nil)),
		},
		Hex: "80ff833210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff853210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff894616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff87061d0100024500ff815816012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d537472756374020601014102030001014202420001014302430001014402440001014502020001014602010000ff82140100020003000401010002000300000501060000",
	},
	{
		Name: "MStruct{D: {A: true, B: \"abc\", C: 123}}",
		Value: MStruct{
			D: &NStruct{
				A: true,
				B: "abc",
				C: 123,
			},
			E: __vdl.TypeOf((*__vdlutil.Any)(nil)),
		},
		Hex: "80ff833210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c020300ff853210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d426f6f6c020300ff894616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b0000ff87061d0100024500ff815816012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d537472756374020601014102030001014202420001014302430001014402440001014502020001014602010000ff821801000200030004010101020361626303fff6000501060000",
	},
	{
		Name: "MList{{4, 2}, {}, {99}}",
		Value: MList{
			{
				4,
				2,
			},
			nil,
			{
				99,
			},
		},
		Hex: "80ff8338130132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4c69737455696e743634020800ff813213012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d4c697374024200ff820703020402000163",
	},
	{
		Name: "MMap{4.5: {2, 3}}",
		Value: MMap{
			4.5: {
				2,
				3,
			},
		},
		Hex: "80ff833510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743332020c00ff8538130132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4c69737455696e743634020800ff813315012b766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4d4d61700242034300ff820701fe1240020203",
	},
	{
		Name:  "typeobject(any)",
		Value: __vdl.TypeOf((*__vdlutil.Any)(nil)),
		Hex:   "800401",
	},
	{
		Name:  "typeobject(bool)",
		Value: __vdl.TypeOf(false),
		Hex:   "800403",
	},
	{
		Name:  "typeobject(uint16)",
		Value: __vdl.TypeOf(uint16(0)),
		Hex:   "800406",
	},
	{
		Name:  "typeobject(uint32)",
		Value: __vdl.TypeOf(uint32(0)),
		Hex:   "800407",
	},
	{
		Name:  "typeobject(uint64)",
		Value: __vdl.TypeOf(uint64(0)),
		Hex:   "800408",
	},
	{
		Name:  "typeobject(int16)",
		Value: __vdl.TypeOf(int16(0)),
		Hex:   "800409",
	},
	{
		Name:  "typeobject(int32)",
		Value: __vdl.TypeOf(int32(0)),
		Hex:   "80040a",
	},
	{
		Name:  "typeobject(int64)",
		Value: __vdl.TypeOf(int64(0)),
		Hex:   "80040b",
	},
	{
		Name:  "typeobject(int16)",
		Value: __vdl.TypeOf(int16(0)),
		Hex:   "800409",
	},
	{
		Name:  "typeobject(int32)",
		Value: __vdl.TypeOf(int32(0)),
		Hex:   "80040a",
	},
	{
		Name:  "typeobject(int64)",
		Value: __vdl.TypeOf(int64(0)),
		Hex:   "80040b",
	},
	{
		Name:  "typeobject(float32)",
		Value: __vdl.TypeOf(float32(0)),
		Hex:   "80040c",
	},
	{
		Name:  "typeobject(float64)",
		Value: __vdl.TypeOf(float64(0)),
		Hex:   "80040d",
	},
	{
		Name:  "typeobject(complex64)",
		Value: __vdl.TypeOf(complex64(0)),
		Hex:   "80040e",
	},
	{
		Name:  "typeobject(complex128)",
		Value: __vdl.TypeOf(complex128(0)),
		Hex:   "80040f",
	},
	{
		Name:  "typeobject(NBool)",
		Value: __vdl.TypeOf(NBool(false)),
		Hex:   "80ff813210012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e426f6f6c0203000441",
	},
	{
		Name:  "typeobject(NUint16)",
		Value: __vdl.TypeOf(NUint16(0)),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e7431360206000441",
	},
	{
		Name:  "typeobject(NUint32)",
		Value: __vdl.TypeOf(NUint32(0)),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e7433320207000441",
	},
	{
		Name:  "typeobject(NUint64)",
		Value: __vdl.TypeOf(NUint64(0)),
		Hex:   "80ff813410012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e55696e7436340208000441",
	},
	{
		Name:  "typeobject(NInt16)",
		Value: __vdl.TypeOf(NInt16(0)),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e7431360209000441",
	},
	{
		Name:  "typeobject(NInt32)",
		Value: __vdl.TypeOf(NInt32(0)),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743332020a000441",
	},
	{
		Name:  "typeobject(NInt64)",
		Value: __vdl.TypeOf(NInt64(0)),
		Hex:   "80ff813310012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e496e743634020b000441",
	},
	{
		Name:  "typeobject(NFloat32)",
		Value: __vdl.TypeOf(NFloat32(0)),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743332020c000441",
	},
	{
		Name:  "typeobject(NFloat64)",
		Value: __vdl.TypeOf(NFloat64(0)),
		Hex:   "80ff813510012f766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e466c6f61743634020d000441",
	},
	{
		Name:  "typeobject(NComplex64)",
		Value: __vdl.TypeOf(NComplex64(0)),
		Hex:   "80ff8137100131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c65783634020e000441",
	},
	{
		Name:  "typeobject(NComplex128)",
		Value: __vdl.TypeOf(NComplex128(0)),
		Hex:   "80ff8138100132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e436f6d706c6578313238020f000441",
	},
	{
		Name:  "typeobject([2]uint64)",
		Value: __vdl.TypeOf([2]uint64{}),
		Hex:   "80ff810812010002080302000441",
	},
	{
		Name:  "typeobject(NArray2Uint64)",
		Value: __vdl.TypeOf(NArray2Uint64{}),
		Hex:   "80ff813c120134766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e41727261793255696e74363402080302000441",
	},
	{
		Name:  "typeobject([]uint64)",
		Value: __vdl.TypeOf([]uint64(nil)),
		Hex:   "80ff81061301000208000441",
	},
	{
		Name:  "typeobject(NListUint64)",
		Value: __vdl.TypeOf(NListUint64(nil)),
		Hex:   "80ff8138130132766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4c69737455696e7436340208000441",
	},
	{
		Name:  "typeobject(set[uint64])",
		Value: __vdl.TypeOf(map[uint64]struct{}(nil)),
		Hex:   "80ff81061401000208000441",
	},
	{
		Name:  "typeobject(NSetUint64)",
		Value: __vdl.TypeOf(NSetUint64(nil)),
		Hex:   "80ff8137140131766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e53657455696e7436340208000441",
	},
	{
		Name:  "typeobject(map[uint64]string)",
		Value: __vdl.TypeOf(map[uint64]string(nil)),
		Hex:   "80ff810815010002080304000441",
	},
	{
		Name:  "typeobject(NMapUint64String)",
		Value: __vdl.TypeOf(NMapUint64String(nil)),
		Hex:   "80ff813f150137766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4d617055696e743634537472696e6702080304000441",
	},
	{
		Name:  "typeobject(NStruct)",
		Value: __vdl.TypeOf(NStruct{}),
		Hex:   "80ff814616012e766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e5374727563740203010141020300010142020400010143020b00000441",
	},
	{
		Name:  "typeobject(NEnum)",
		Value: __vdl.TypeOf(NEnumA),
		Hex:   "80ff813811012c766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e456e756d0203014101420143000441",
	},
	{
		Name:  "typeobject(NOneOf)",
		Value: __vdl.TypeOf(NOneOf(NOneOfA{false})),
		Hex:   "80ff814519012d766579726f6e2e696f2f766579726f6e2f766579726f6e322f766f6d322f74657374646174612e4e4f6e654f660203010141020300010142020400010143020b00000441",
	},
}
